from __future__ import annotations

from app.core.enums import RoleKey

DEFAULT_PERMISSIONS = {
    "audit.view": "View audit trail and action history",
    "destructive.manage": "Run guarded corrective hard-delete actions",
    "period_lock.manage": "Set and edit closing-date period locks",
    "users.manage": "Manage all users and roles",
    "users.self_manage": "Manage own profile",
    "settings.manage": "Manage settings and backups",
    "finance.view": "View finance dashboard metrics",
    "reports.view": "View broader operational reports",
    "exports.view": "Download and open exports",
    "exports.manage": "Manage saved export schedules",
    "accounting.view": "View accounting foundation data",
    "accounting.manage": "Create, post, and reverse journal entries",
    "customers.view": "View customers list and details",
    "customers.manage": "Create and update customers",
    "catalog.view": "View departments and services catalog",
    "catalog.manage": "Create and update departments and services",
    "dresses.view": "View dress resources",
    "dresses.manage": "Create and update dress resources",
    "bookings.view": "View bookings",
    "bookings.manage": "Create and update bookings",
    "payments.view": "View payments",
    "payments.manage": "Create and update payments",
    "custody.view": "View custody cases",
    "custody.manage": "Create and manage custody workflows",
}

ROLE_PERMISSION_MAP = {
    RoleKey.ADMIN.value: [
        "audit.view",
        "destructive.manage",
        "period_lock.manage",
        "users.manage",
        "users.self_manage",
        "settings.manage",
        "finance.view",
        "reports.view",
        "exports.view",
        "exports.manage",
        "accounting.view",
        "accounting.manage",
        "customers.view",
        "customers.manage",
        "catalog.view",
        "catalog.manage",
        "dresses.view",
        "dresses.manage",
        "bookings.view",
        "bookings.manage",
        "payments.view",
        "payments.manage",
        "custody.view",
        "custody.manage",
    ],
    RoleKey.USER.value: [
        "users.self_manage",
        "settings.manage",
        "finance.view",
        "reports.view",
        "accounting.view",
        "customers.view",
        "customers.manage",
        "catalog.view",
        "catalog.manage",
        "dresses.view",
        "dresses.manage",
        "bookings.view",
        "bookings.manage",
        "payments.view",
        "payments.manage",
        "custody.view",
        "custody.manage",
    ],
}
