import { useLocalizedText } from './useText';

const auditText = {
  ar: {
    page: {
      title: 'مستكشف التدقيق',
      subtitle: 'بحث وتتبع أحداث النظام حسب المستخدم والإجراء والكيان والتاريخ.',
      search: 'بحث',
      actorUserId: 'معرف المستخدم',
      action: 'الإجراء',
      targetType: 'نوع الكيان',
      targetId: 'معرف الكيان',
      branchId: 'معرف الفرع',
      dateFrom: 'من تاريخ',
      dateTo: 'إلى تاريخ',
      quickRanges: 'مدى زمني سريع',
      today: 'اليوم',
      last24h: 'آخر 24 ساعة',
      last7d: 'آخر 7 أيام',
      exportNightlyCsv: 'تصدير CSV (التشغيل الليلي)',
      exportReasonPrompt: 'سبب التصدير (اختياري)',
      exportRows: 'الصفوف المطابقة',
      exportFilters: 'الفلاتر النشطة',
      noActiveFilters: 'لا توجد فلاتر نشطة',
      applyFilters: 'تطبيق الفلاتر',
      resetFilters: 'إعادة التصفية',
      destructiveOnly: 'العمليات التدميرية فقط',
      nightlyOps: 'متابعة التشغيل الليلي',
      allActions: 'كل العمليات',
      occurredAt: 'الوقت',
      actor: 'المنفذ',
      entity: 'الكيان',
      summary: 'الملخص',
      status: 'النتيجة',
      noRows: 'لا توجد أحداث مطابقة.',
    },
  },
  en: {
    page: {
      title: 'Audit explorer',
      subtitle: 'Search and track system events by actor, action, entity, and date.',
      search: 'Search',
      actorUserId: 'Actor user ID',
      action: 'Action',
      targetType: 'Target type',
      targetId: 'Target ID',
      branchId: 'Branch ID',
      dateFrom: 'Date from',
      dateTo: 'Date to',
      quickRanges: 'Quick date range',
      today: 'Today',
      last24h: 'Last 24h',
      last7d: 'Last 7d',
      exportNightlyCsv: 'Export nightly CSV',
      exportReasonPrompt: 'Export reason (optional)',
      exportRows: 'Matching rows',
      exportFilters: 'Active filters',
      noActiveFilters: 'No active filters',
      applyFilters: 'Apply filters',
      resetFilters: 'Reset filters',
      destructiveOnly: 'Destructive only',
      nightlyOps: 'Nightly ops',
      allActions: 'All actions',
      occurredAt: 'Occurred at',
      actor: 'Actor',
      entity: 'Entity',
      summary: 'Summary',
      status: 'Status',
      noRows: 'No matching events.',
    },
  },
} as const;

export function useAuditText() {
  return useLocalizedText(auditText);
}
