import { useLocalizedText } from './useText';

const bookingsText = {
  ar: {
    page: {
      createDocument: 'إنشاء وثيقة حجز',
      editorSubtitle: 'أنشئ أو عدّل الوثيقة ثم أضف سطور الخدمات وحدد الأسعار والدفعات الأولية من مكان واحد.',
      editorTitle: 'محرر وثيقة الحجز',
      listSubtitle: 'يعرض كل صف وثيقة حجز واحدة مع ملخص السطور والمبالغ والحالة العامة.',
      listTitle: 'قائمة وثائق الحجز',
      openDocument: 'فتح الوثيقة',
      subtitle: 'إدارة وثائق الحجز متعددة السطور مع متابعة حالة كل خدمة والمدفوعات المرتبطة بها.',
      title: 'وثائق الحجز',
    },
    table: {
      bookingNumber: 'رقم الحجز',
      customer: 'العميل',
      lineCount: 'عدد السطور',
      nextServiceDate: 'أقرب تاريخ خدمة',
      paid: 'المدفوع',
      remaining: 'المتبقي',
      serviceSummary: 'ملخص الخدمات',
      status: 'الحالة',
      total: 'الإجمالي',
    },
    editor: {
      addCustomer: 'إضافة عميل',
      addLine: 'إضافة سطر',
      bookingDate: 'تاريخ الحجز',
      cancelLine: 'إلغاء السطر',
      completeLine: 'إكمال',
      createTitle: 'وثيقة حجز جديدة',
      customer: 'العميل',
      deleteLine: 'حذف',
      linesTitle: 'سطور الوثيقة',
      noDress: 'بدون فستان',
      notes: 'ملاحظات الوثيقة',
      revenueEntryPrefix: 'قيد',
      save: 'حفظ الوثيقة',
      subtitle: 'عميل واحد مع عدة سطور خدمات وأسعار ودفعات أولية اختيارية من شاشة واحدة.',
      summaryLabels: {
        paid: 'المدفوع',
        remaining: 'المتبقي',
        status: 'الحالة',
        total: 'الإجمالي',
      },
      summaryPrefix: 'ملخص الوثيقة',
      updateTitlePrefix: 'وثيقة الحجز',
    },
    lineTable: {
      department: 'القسم',
      dress: 'الفستان',
      initialPayment: 'الدفعة الأولى',
      linePrice: 'السعر الفعلي',
      paid: 'المدفوع',
      remaining: 'المتبقي',
      service: 'الخدمة',
      serviceDate: 'تاريخ الخدمة',
      status: 'الحالة',
      suggestedPrice: 'السعر المقترح',
    },
    quickCustomer: {
      address: 'العنوان',
      email: 'البريد الإلكتروني',
      fullName: 'الاسم الكامل',
      notes: 'ملاحظات',
      phone: 'الهاتف',
      save: 'حفظ العميل',
      title: 'إضافة عميل سريع',
    },
  },
  en: {
    page: {
      createDocument: 'Create booking document',
      editorSubtitle: 'Create or update the document, then add service lines, prices, and initial payments in one place.',
      editorTitle: 'Booking document editor',
      listSubtitle: 'Each row shows one booking document with line, amount, and status summaries.',
      listTitle: 'Booking documents',
      openDocument: 'Open document',
      subtitle: 'Manage multi-line booking documents and track each service line with its linked payments.',
      title: 'Booking documents',
    },
    table: {
      bookingNumber: 'Booking #',
      customer: 'Customer',
      lineCount: 'Lines',
      nextServiceDate: 'Next service date',
      paid: 'Paid',
      remaining: 'Remaining',
      serviceSummary: 'Service summary',
      status: 'Status',
      total: 'Total',
    },
    editor: {
      addCustomer: 'Add customer',
      addLine: 'Add line',
      bookingDate: 'Booking date',
      cancelLine: 'Cancel line',
      completeLine: 'Complete',
      createTitle: 'New booking document',
      customer: 'Customer',
      deleteLine: 'Delete',
      linesTitle: 'Document lines',
      noDress: 'No dress',
      notes: 'Document notes',
      revenueEntryPrefix: 'Entry',
      save: 'Save document',
      subtitle: 'One customer with multiple service lines, prices, and optional initial payments from a single screen.',
      summaryLabels: {
        paid: 'Paid',
        remaining: 'Remaining',
        status: 'Status',
        total: 'Total',
      },
      summaryPrefix: 'Document summary',
      updateTitlePrefix: 'Booking document',
    },
    lineTable: {
      department: 'Department',
      dress: 'Dress',
      initialPayment: 'Initial payment',
      linePrice: 'Actual price',
      paid: 'Paid',
      remaining: 'Remaining',
      service: 'Service',
      serviceDate: 'Service date',
      status: 'Status',
      suggestedPrice: 'Suggested price',
    },
    quickCustomer: {
      address: 'Address',
      email: 'Email',
      fullName: 'Full name',
      notes: 'Notes',
      phone: 'Phone',
      save: 'Save customer',
      title: 'Quick customer',
    },
  },
} as const;

export function useBookingsText() {
  return useLocalizedText(bookingsText);
}
