import { useLocalizedText } from './useText';

const customersText = {
  ar: {
    page: {
      create: 'إضافة عميل',
      description: 'إدارة قائمة العملاء الأساسية بنفس أسلوب النظام السابق ولكن على البنية الجديدة.',
      listSubtitle: 'يمكن للمدير والمستخدم العادي عرض العملاء وإضافتهم وتعديلهم في هذه المرحلة.',
      listTitle: 'قائمة العملاء',
      title: 'العملاء',
    },
    table: {
      action: 'إجراء',
      email: 'البريد',
      fullName: 'الاسم الكامل',
      groomName: 'اسم العريس',
      brideName: 'اسم العروسة',
      phone: 'الهاتف 1',
      phone2: 'الهاتف 2',
      status: 'الحالة',
    },
    dialog: {
      create: 'إضافة عميل',
      edit: 'تعديل عميل',
      address: 'العنوان',
      email: 'البريد الإلكتروني',
      fullName: 'الاسم الكامل',
      groomName: 'اسم العريس',
      brideName: 'اسم العروسة',
      notes: 'ملاحظات',
      phone: 'رقم تليفون 1',
      phone2: 'رقم تليفون 2',
      status: 'الحالة',
    },
    status: {
      active: 'نشط',
      inactive: 'موقوف',
    },
    statement: {
      title: 'كشف حساب وملخص حركات العميل',
      subtitle: 'ملخص مالي وتفاصيل الحجوزات والخدمات والمقبوضات ودفتر الأستاذ',
      actionBtn: 'كشف حساب',
      totalBookings: 'إجمالي الحجوزات',
      totalCollections: 'إجمالي المقبوضات',
      totalRefunds: 'المسترد',
      remainingBalance: 'الرصيد المتبقي المستحق',
      ledgerBalance: 'الرصيد المحاسبي',
      tabs: {
        services: 'الحجوزات والخدمات',
        payments: 'المقبوضات والتحصيلات',
        ledger: 'دفتر الأستاذ والقيود',
      },
      printBtn: 'عرض الطباعة',
      exportExcel: 'تصدير إكسيل',
      noMovements: 'لا توجد حركات مسجلة للعميل حتى الآن',
      bookingNo: 'رقم الحجز',
      bookingDate: 'تاريخ الحجز',
      serviceDate: 'تاريخ الخدمة',
      serviceName: 'الخدمة / الفستان',
      branch: 'الفرع',
      totalAmount: 'الإجمالي',
      paidAmount: 'المدفوع',
      remaining: 'المتبقي',
      paymentNo: 'رقم السند',
      paymentDate: 'تاريخ السند',
      paymentMethod: 'طريقة الدفع',
      entryNo: 'رقم القيد',
      entryDate: 'التاريخ',
      debit: 'مدين',
      credit: 'دائن',
      runningBalance: 'الرصيد المتراكم',
      description: 'البيان',
    },
  },
  en: {
    page: {
      create: 'Add customer',
      description: 'Manage the core customer list in the same spirit as the previous system on the new architecture.',
      listSubtitle: 'Both admin and regular users can view, create, and update customers at this stage.',
      listTitle: 'Customers list',
      title: 'Customers',
    },
    table: {
      action: 'Action',
      email: 'Email',
      fullName: 'Full name',
      groomName: "Groom's Name",
      brideName: "Bride's Name",
      phone: 'Phone 1',
      phone2: 'Phone 2',
      status: 'Status',
    },
    dialog: {
      create: 'Create customer',
      edit: 'Edit customer',
      address: 'Address',
      email: 'Email',
      fullName: 'Full name',
      groomName: "Groom's Name",
      brideName: "Bride's Name",
      notes: 'Notes',
      phone: 'Phone 1',
      phone2: 'Phone 2',
      status: 'Status',
    },
    status: {
      active: 'Active',
      inactive: 'Inactive',
    },
    statement: {
      title: 'Customer Financial Statement & Summary',
      subtitle: 'Financial summary, bookings, service dates, collections, and general ledger',
      actionBtn: 'Statement',
      totalBookings: 'Total Bookings',
      totalCollections: 'Total Collections',
      totalRefunds: 'Refunds',
      remainingBalance: 'Remaining Balance',
      ledgerBalance: 'Ledger Balance',
      tabs: {
        services: 'Bookings & Services',
        payments: 'Collections & Payments',
        ledger: 'General Ledger',
      },
      printBtn: 'Print View',
      exportExcel: 'Export Excel',
      noMovements: 'No activity records found for this customer.',
      bookingNo: 'Booking #',
      bookingDate: 'Booking Date',
      serviceDate: 'Service Date',
      serviceName: 'Service / Dress',
      branch: 'Branch',
      totalAmount: 'Total',
      paidAmount: 'Paid',
      remaining: 'Remaining',
      paymentNo: 'Payment #',
      paymentDate: 'Payment Date',
      paymentMethod: 'Payment Method',
      entryNo: 'Entry #',
      entryDate: 'Date',
      debit: 'Debit',
      credit: 'Credit',
      runningBalance: 'Running Balance',
      description: 'Description',
    },
  },
} as const;

export function useCustomersText() {
  return useLocalizedText(customersText);
}
