import { useLocalizedText } from './useText';

const custodyText = {
  ar: {
    page: {
      title: 'استلام وتسليم الفساتين',
      subtitle: 'متابعة حالات الحيازة في جدول موحد مع عرض مرن حسب الحالة.',
      createTitle: 'إنشاء حيازة جديدة',
      createSubtitle: 'أدخل بيانات الحيازة الأساسية وحدد تاريخ الإدخال.',
      listTitle: 'جدول الحيازة',
      listSubtitle: 'حالة الحيازة المفتوحة والمنتهية والكل في جدول واحد.',
      created: 'تم إنشاء حالة الحيازة بنجاح.',
      notes: 'ملاحظات الحيازة',
      productCondition: 'حالة المنتج',
      create: 'إنشاء الحالة',
      actionTitle: 'تحديث مرحلة الحيازة',
      actionSubtitle: 'اختر الحالة والإجراء والتاريخ ثم نفّذ المرحلة.',
      targetCase: 'الحالة المستهدفة',
      action: 'الإجراء',
      actionDate: 'تاريخ المرحلة',
      actionNote: 'ملاحظة الإجراء',
      applyAction: 'تنفيذ الإجراء',
      compensationTitle: 'تحصيل تعويض الحيازة',
      compensationSubtitle: 'تحصيل مبلغ التعويض وإنشاء سند مالي مرتبط بالحالة.',
      compensationAmount: 'مبلغ التعويض',
      paymentMethod: 'طريقة الدفع',
      compensationDate: 'تاريخ التحصيل',
      compensationNote: 'ملاحظة التعويض',
      compensationApply: 'تحصيل التعويض',
      caseNumber: 'رقم الحالة',
      custodyDate: 'تاريخ الحيازة',
      status: 'الحالة',
      customerName: 'اسم العميل',
      bookingNumber: 'رقم الحجز',
      dressCode: 'الفستان',
      statement: 'البيان',
      depositAmount: 'مبلغ التأمين',
      compensationValue: 'مبلغ التعويض',
      viewOpen: 'حيازة مفتوحة',
      viewSettled: 'حيازة منتهية',
      viewAll: 'عرض الكل',
      emptyValue: '-',
    },
  },
  en: {
    page: {
      title: 'Dress custody handover',
      subtitle: 'Track custody cases in one unified table with status views.',
      createTitle: 'Create new custody case',
      createSubtitle: 'Enter base custody data and choose entry date.',
      listTitle: 'Custody table',
      listSubtitle: 'Open, settled, and all custody rows in one grid.',
      created: 'Custody case created successfully.',
      notes: 'Custody notes',
      productCondition: 'Product condition',
      create: 'Create case',
      actionTitle: 'Update custody stage',
      actionSubtitle: 'Select case, action, and stage date, then apply.',
      targetCase: 'Target case',
      action: 'Action',
      actionDate: 'Stage date',
      actionNote: 'Action note',
      applyAction: 'Apply action',
      compensationTitle: 'Collect custody compensation',
      compensationSubtitle: 'Collect compensation and create linked payment document.',
      compensationAmount: 'Compensation amount',
      paymentMethod: 'Payment method',
      compensationDate: 'Collection date',
      compensationNote: 'Compensation note',
      compensationApply: 'Collect compensation',
      caseNumber: 'Case number',
      custodyDate: 'Custody date',
      status: 'Status',
      customerName: 'Customer name',
      bookingNumber: 'Booking number',
      dressCode: 'Dress',
      statement: 'Statement',
      depositAmount: 'Deposit amount',
      compensationValue: 'Compensation amount',
      viewOpen: 'Open custody',
      viewSettled: 'Settled custody',
      viewAll: 'Show all',
      emptyValue: '-',
    },
  },
} as const;

export function useCustodyText() {
  return useLocalizedText(custodyText);
}
