import { useLocalizedText } from './useText';

const paymentsText = {
  ar: {
    page: {
      accountingChip: 'سندات دفع متعددة التوزيع',
      addMultiAction: 'إضافة سند دفع متعدد',
      edit: 'تعديل',
      listSubtitle: 'كل صف يمثل سند دفع واحدًا مع ملخص التوزيع والحالة والقيد المحاسبي المرتبط.',
      listTitle: 'قائمة سندات الدفع',
      searchHint: 'اكتب حرفين على الأقل لبدء البحث.',
      searchLoading: 'جاري تحميل نتائج البحث...',
      searchLabel: 'ابحث باسم العميل أو رقم الحجز',
      searchNoResults: 'لم يتم العثور على نتائج مطابقة للبحث.',
      searchCustomerTag: 'عميل',
      searchBookingTag: 'حجز',
      searchSubtitle: 'ابدأ باختيار عميل أو حجز ثم افتح شاشة توزيع المبلغ على السطور المفتوحة.',
      searchTitle: 'بحث الدفع',
      subtitle: 'ابحث باسم العميل أو رقم الحجز لإنشاء سند دفع واحد يوزع على أكثر من سطر خدمة.',
      targetSubtitle: 'اختر عميلًا أو حجزًا لفتح سند دفع واحد وتوزيع المبلغ على السطور المفتوحة.',
      targetTitle: 'محرر سند الدفع',
      title: 'سندات الدفع',
      void: 'إبطال',
      voidedState: 'تم الإبطال',
    },
    overview: {
      title: 'نظرة سريعة للمدفوعات',
      subtitle: 'ملخص يعتمد على الفلاتر النشطة حاليًا.',
      loading: 'جاري تحميل ملخص الشاشة...',
      totalDocuments: 'إجمالي السندات',
      totalDocumentsHelper: 'حسب نتيجة التصفية الحالية',
      activeDocuments: 'سندات نشطة',
      activeAmount: 'مبلغ السندات النشطة',
      voidedAmount: 'مبلغ السندات الملغاة',
      currentPageHelper: 'من صفحة العرض الحالية',
    },
    table: {
      bookings: 'الحجوزات',
      customer: 'العميل',
      paymentMethod: 'طريقة الدفع',
      date: 'التاريخ',
      journal: 'القيد',
      number: 'رقم السند',
      status: 'الحالة',
      total: 'الإجمالي',
      type: 'النوع',
    },
    builder: {
      allocationAmount: 'مبلغ التخصيص',
      editNotice: 'أنت الآن تعدل سندًا موجودًا. سيتم عكس القيد المحاسبي القديم وإنشاء قيد بديل عند الحفظ.',
      notes: 'ملاحظات السند',
      paymentMethod: 'طريقة الدفع',
      paymentDate: 'تاريخ السند',
      save: 'حفظ السند',
      scopeSummaryPrefix: 'العميل',
      selectedTotal: 'إجمالي المبلغ المخصص',
      subtitle: 'سند واحد يوزع المبلغ على سطور الخدمات المفتوحة لنفس العميل والفرع النشط.',
      title: 'إنشاء سند دفع',
      updateTitlePrefix: 'تحرير سند',
    },
    allocationTable: {
      allocationAmount: 'مبلغ التخصيص',
      booking: 'الحجز',
      department: 'القسم',
      dress: 'الفستان',
      lineNumber: 'السطر',
      paymentState: 'حالة الدفع',
      price: 'السعر',
      remaining: 'المتبقي',
      service: 'الخدمة',
      serviceDate: 'تاريخ الخدمة',
      status: 'الحالة',
    },
    summary: {
      branch: 'الفرع',
      documentTotal: 'إجمالي الوثيقة',
      paid: 'المدفوع',
      remaining: 'المتبقي',
      totalOpen: 'إجمالي المتبقي المفتوح',
      status: 'الحالة',
    },
    voidDialog: {
      confirm: 'تأكيد الإبطال',
      date: 'تاريخ الإبطال',
      reason: 'سبب الإبطال',
      title: 'إبطال دفعة',
      warningSuffix: 'وسيتم عكس قيدها المحاسبي بدل حذفها.',
    },
  },
  en: {
    page: {
      accountingChip: 'Multi-allocation payment documents',
      addMultiAction: 'Add multi-allocation payment',
      edit: 'Edit',
      listSubtitle: 'Each row represents one payment document with allocation summary, status, and linked journal entry.',
      listTitle: 'Payment documents',
      searchHint: 'Type at least two characters to start searching.',
      searchLoading: 'Loading search results...',
      searchLabel: 'Search by customer name or booking number',
      searchNoResults: 'No matching customer or booking was found.',
      searchCustomerTag: 'Customer',
      searchBookingTag: 'Booking',
      searchSubtitle: 'Start by selecting a customer or booking, then open the allocation screen for open lines.',
      searchTitle: 'Payment search',
      subtitle: 'Search by customer or booking number to create one payment document allocated across multiple service lines.',
      targetSubtitle: 'Choose a customer or booking to open one payment document and distribute the amount across open lines.',
      targetTitle: 'Payment document editor',
      title: 'Payment documents',
      void: 'Void',
      voidedState: 'Voided',
    },
    overview: {
      title: 'Payment quick overview',
      subtitle: 'Snapshot based on the current active filters.',
      loading: 'Loading overview...',
      totalDocuments: 'Total documents',
      totalDocumentsHelper: 'Across current filtered result set',
      activeDocuments: 'Active documents',
      activeAmount: 'Active amount',
      voidedAmount: 'Voided amount',
      currentPageHelper: 'From the current visible page',
    },
    table: {
      bookings: 'Bookings',
      customer: 'Customer',
      paymentMethod: 'Payment method',
      date: 'Date',
      journal: 'Journal',
      number: 'Document #',
      status: 'Status',
      total: 'Total',
      type: 'Type',
    },
    builder: {
      allocationAmount: 'Allocation amount',
      editNotice: 'You are editing an existing payment document. The old journal entry will be reversed and replaced on save.',
      notes: 'Document notes',
      paymentMethod: 'Payment method',
      paymentDate: 'Document date',
      save: 'Save document',
      scopeSummaryPrefix: 'Customer',
      selectedTotal: 'Allocated total',
      subtitle: 'One document distributes an amount across open service lines for the same customer and active branch.',
      title: 'Create payment document',
      updateTitlePrefix: 'Edit document',
    },
    allocationTable: {
      allocationAmount: 'Allocation amount',
      booking: 'Booking',
      department: 'Department',
      dress: 'Dress',
      lineNumber: 'Line',
      paymentState: 'Payment state',
      price: 'Price',
      remaining: 'Remaining',
      service: 'Service',
      serviceDate: 'Service date',
      status: 'Status',
    },
    summary: {
      branch: 'Branch',
      documentTotal: 'Document total',
      paid: 'Paid',
      remaining: 'Remaining',
      totalOpen: 'Open remaining total',
      status: 'Status',
    },
    voidDialog: {
      confirm: 'Confirm void',
      date: 'Void date',
      reason: 'Void reason',
      title: 'Void payment',
      warningSuffix: 'and reverse its linked journal entry instead of deleting it.',
    },
  },
} as const;

export function usePaymentsText() {
  return useLocalizedText(paymentsText);
}
