import type { LanguageCode } from '../lib/language';
import { useLocalizedText } from './useText';

const reportsText = {
  ar: {
    page: {
      button: 'عرض ملخص تشغيلي',
      description: 'ملخص تشغيلي أوسع يغطي العملاء والخدمات والفساتين والحجوزات والمدفوعات.',
      title: 'التقارير',
    },
    metrics: {
      activeCustomers: 'العملاء النشطون',
      activeServices: 'الخدمات النشطة',
      availableDresses: 'الفساتين المتاحة',
      upcomingBookings: 'الحجوزات القادمة',
    },
    helpers: {
      activeCustomers: 'عدد العملاء النشطين داخل النظام.',
      activeServices: 'عدد الخدمات المتاحة حاليًا.',
      availableDresses: 'الفساتين الجاهزة للحجز الآن.',
      upcomingBookings: 'الحجوزات غير الملغاة القادمة.',
    },
    sections: {
      bookingStatuses: 'حالات الحجوزات',
      departmentServices: 'الخدمات حسب القسم',
      dressStatuses: 'حالات الفساتين',
      paymentMix: 'خلطة المدفوعات',
      upcoming: 'أقرب الحجوزات القادمة',
    },
    table: {
      bookingNumber: 'رقم الحجز',
      customer: 'العميل',
      service: 'الخدمة',
      serviceDate: 'تاريخ الخدمة',
      status: 'الحالة',
    },
    subtitles: {
      bookingStatuses: 'تجميع الحجوزات حسب الحالة.',
      departmentServices: 'عدد الخدمات داخل كل قسم.',
      dressStatuses: 'توزيع الفساتين حسب حالتها الحالية.',
      empty: 'لا توجد بيانات بعد.',
      paymentMix: 'صافي المدفوعات بحسب نوع الحركة.',
      servicesCountSuffix: 'خدمات',
      upcoming: 'أول الحجوزات القادمة بحسب التاريخ.',
      itemsSuffix: 'عناصر',
    },
    print: {
      noData: 'لا توجد بيانات.',
      subtitle: 'نسخة مناسبة للطباعة أو الحفظ PDF من صفحة التقارير.',
      title: 'تقرير تشغيلي قابل للطباعة',
    },
    comprehensive: {
      pageTitle: 'التقارير الشاملة',
      pageSubtitle: 'مؤشرات الأداء والإيرادات والحجوزات لنطاق زمني مخصص.',
      filterTitle: 'نطاق التقرير',
      today: 'اليوم',
      yesterday: 'أمس',
      last7: 'آخر 7 أيام',
      last14: 'آخر 14 يوماً',
      last30: 'آخر 30 يوماً',
      thisMonth: 'هذا الشهر',
      lastMonth: 'الشهر الماضي',
      thisYear: 'هذه السنة',
      all: 'الكل (من البداية)',
      custom: 'مخصص',
      from: 'من تاريخ',
      to: 'إلى تاريخ',
      apply: 'تطبيق',
      totalCollected: 'إجمالي المحصل',
      totalCollectedHelper: 'صافي الدفعات المحصلة بعد خصم الاستردادات.',
      totalRecognized: 'الإيراد المعترف به',
      totalRecognizedHelper: 'الإيرادات المحققة من الحجوزات المكتملة.',
      totalRemaining: 'إجمالي المتبقي',
      totalRemainingHelper: 'المبالغ المتبقية على الحجوزات النشطة.',
      totalBookings: 'عدد الحجوزات',
      totalBookingsHelper: 'إجمالي الحجوزات في النطاق الزمني.',
      cancellationRate: 'نسبة الإلغاء',
      cancellationRateHelper: 'نسبة الحجوزات الملغاة من الإجمالي.',
      dailyIncome: 'الدخل اليومي',
      dailyIncomeSubtitle: 'صافي المبالغ المحصلة يومياً في النطاق الزمني.',
      deptIncome: 'الدخل حسب القسم',
      deptIncomeSubtitle: 'صافي الدخل موزعاً على الأقسام.',
      topServices: 'أكثر الخدمات طلباً',
      topServicesSubtitle: 'الخدمات الأكثر حجزاً حسب عدد سطور الحجز.',
      topClients: 'أفضل العملاء',
      topClientsSubtitle: 'أعلى 10 عملاء من حيث المبالغ المحصلة.',
      clientName: 'اسم العميل',
      amountPaid: 'المبلغ المحصل',
      bookingCount: 'الحجوزات',
      bookingStatuses: 'حالات الحجوزات',
      bookingStatusesSubtitle: 'توزيع الحجوزات حسب الحالة.',
      noData: 'لا توجد بيانات للنطاق الزمني المختار.',
      exportCSV: 'تصدير CSV',
      exportExcel: 'تصدير Excel',
      exportPDF: 'طباعة / PDF',
      tabs: {
        overview: 'نظرة عامة',
        detailed: 'البيانات التفصيلية',
      },
      detailedTable: {
        title: 'البيانات التفصيلية (كل الحجوزات)',
        subtitle: 'قائمة بكافة تفاصيل سطور الحجوزات، المبالغ، والتواريخ في النطاق الزمني.',
        bookingId: 'رقم الحجز',
        externalCode: 'الكود المرجعي',
        bookingDate: 'تاريخ الحجز',
        customerName: 'العميل',
        customerPhone: 'رقم الهاتف',
        department: 'القسم',
        service: 'الخدمة',
        dressCode: 'كود الفستان',
        serviceDate: 'تاريخ المناسبة / الخدمة',
        linePrice: 'سعر الخدمة',
        paidAmount: 'المدفوع',
        remainingAmount: 'المتبقي',
        bookingStatus: 'حالة الحجز',
        lineStatus: 'حالة السطر',
        notes: 'ملاحظات',
      },
    },
  },
  en: {
    page: {
      button: 'Show operational summary',
      description: 'A broader operational summary across customers, services, dresses, bookings, and payments.',
      title: 'Reports',
    },
    metrics: {
      activeCustomers: 'Active customers',
      activeServices: 'Active services',
      availableDresses: 'Available dresses',
      upcomingBookings: 'Upcoming bookings',
    },
    helpers: {
      activeCustomers: 'Number of active customers in the system.',
      activeServices: 'Number of currently available services.',
      availableDresses: 'Dresses ready to be booked now.',
      upcomingBookings: 'Upcoming non-cancelled bookings.',
    },
    sections: {
      bookingStatuses: 'Booking statuses',
      departmentServices: 'Services by department',
      dressStatuses: 'Dress statuses',
      paymentMix: 'Payment mix',
      upcoming: 'Upcoming bookings',
    },
    table: {
      bookingNumber: 'Booking #',
      customer: 'Customer',
      service: 'Service',
      serviceDate: 'Service date',
      status: 'Status',
    },
    subtitles: {
      bookingStatuses: 'Bookings grouped by status.',
      departmentServices: 'Number of services in each department.',
      dressStatuses: 'Distribution of dresses by current status.',
      empty: 'No data yet.',
      paymentMix: 'Net payment mix by movement type.',
      servicesCountSuffix: 'services',
      upcoming: 'The nearest upcoming bookings by date.',
      itemsSuffix: 'items',
    },
    print: {
      noData: 'No data available.',
      subtitle: 'A printable or PDF-friendly version of the reports page.',
      title: 'Printable operational report',
    },
    comprehensive: {
      pageTitle: 'Comprehensive Reports',
      pageSubtitle: 'KPIs, revenue, and booking metrics for a selected date range.',
      filterTitle: 'Report Range',
      today: 'Today',
      yesterday: 'Yesterday',
      last7: 'Last 7 days',
      last14: 'Last 14 days',
      last30: 'Last 30 days',
      thisMonth: 'This month',
      lastMonth: 'Last month',
      thisYear: 'This year',
      all: 'All Time',
      custom: 'Custom',
      from: 'From',
      to: 'To',
      apply: 'Apply',
      totalCollected: 'Total Collected',
      totalCollectedHelper: 'Net payments received after refunds.',
      totalRecognized: 'Revenue Recognized',
      totalRecognizedHelper: 'Revenue earned from completed bookings.',
      totalRemaining: 'Total Remaining',
      totalRemainingHelper: 'Outstanding balances on active bookings.',
      totalBookings: 'Total Bookings',
      totalBookingsHelper: 'All bookings in the selected date range.',
      cancellationRate: 'Cancellation Rate',
      cancellationRateHelper: 'Percentage of cancelled bookings.',
      dailyIncome: 'Daily Income',
      dailyIncomeSubtitle: 'Net collected amounts per day in the selected range.',
      deptIncome: 'Income by Department',
      deptIncomeSubtitle: 'Net income distributed across departments.',
      topServices: 'Most Booked Services',
      topServicesSubtitle: 'Services with the most booking lines.',
      topClients: 'Top Clients',
      topClientsSubtitle: 'Top 10 clients by total amount collected.',
      clientName: 'Client Name',
      amountPaid: 'Amount Paid',
      bookingCount: 'Bookings',
      bookingStatuses: 'Booking Statuses',
      bookingStatusesSubtitle: 'Distribution of bookings by status.',
      noData: 'No data for the selected date range.',
      exportCSV: 'Export CSV',
      exportExcel: 'Export Excel',
      exportPDF: 'Print / PDF',
      tabs: {
        overview: 'Overview',
        detailed: 'Detailed Data',
      },
      detailedTable: {
        title: 'Detailed Data (All Bookings)',
        subtitle: 'A complete list of all booking lines, amounts, and dates in the selected range.',
        bookingId: 'Booking #',
        externalCode: 'External Code',
        bookingDate: 'Booking Date',
        customerName: 'Customer',
        customerPhone: 'Phone',
        department: 'Department',
        service: 'Service',
        dressCode: 'Dress Code',
        serviceDate: 'Service/Event Date',
        linePrice: 'Line Price',
        paidAmount: 'Paid Amount',
        remainingAmount: 'Remaining',
        bookingStatus: 'Booking Status',
        lineStatus: 'Line Status',
        notes: 'Notes',
      },
    },
  },
} as const;

const reportStatusLabels = {
  ar: {
    available: 'متاح',
    cancelled: 'ملغي',
    completed: 'مكتمل',
    confirmed: 'مؤكد',
    deposit: 'عربون',
    draft: 'مسودة',
    maintenance: 'صيانة',
    payment: 'دفعة',
    refund: 'استرداد',
    reserved: 'محجوز',
    sold: 'مباع',
  },
  en: {
    available: 'Available',
    cancelled: 'Cancelled',
    completed: 'Completed',
    confirmed: 'Confirmed',
    deposit: 'Deposit',
    draft: 'Draft',
    maintenance: 'Maintenance',
    payment: 'Payment',
    refund: 'Refund',
    reserved: 'Reserved',
    sold: 'Sold',
  },
} as const;

export function useReportsText() {
  return useLocalizedText(reportsText);
}

export function reportStatusLabel(language: LanguageCode, value: string) {
  return reportStatusLabels[language][value as keyof typeof reportStatusLabels.ar] ?? value;
}
