"""add_user_theme_preferences

Revision ID: 1503cf864b17
Revises: 848b7989e897
Create Date: 2026-04-26 13:31:13.277718
"""
from alembic import op
import sqlalchemy as sa


revision = '1503cf864b17'
down_revision = '848b7989e897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_theme_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_theme_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_theme_preferences')),
    sa.UniqueConstraint('user_id', name='uq_user_theme_preferences_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_theme_preferences')
    # ### end Alembic commands ###