"""add_cash_reconciliation_feature

Revision ID: 1629a09ff94b
Revises: a833e028fffb
Create Date: 2026-05-17 17:14:59.902967
"""
from alembic import op
import sqlalchemy as sa


revision = '1629a09ff94b'
down_revision = 'a833e028fffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_reconciliations',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('updated_by_user_id', sa.String(), nullable=True),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.Column('receiver_name', sa.Text(), nullable=True),
    sa.Column('total_expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cash_reconciliations_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cash_reconciliations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_cash_reconciliations_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_cash_reconciliations_payment_method_id_payment_methods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_cash_reconciliations_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_reconciliations'))
    )
    op.create_table('reconciliation_items',
    sa.Column('reconciliation_id', sa.String(), nullable=False),
    sa.Column('payment_document_id', sa.String(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_document_id'], ['payment_documents.id'], name=op.f('fk_reconciliation_items_payment_document_id_payment_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['cash_reconciliations.id'], name=op.f('fk_reconciliation_items_reconciliation_id_cash_reconciliations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_items')
    op.drop_table('cash_reconciliations')
    # ### end Alembic commands ###