"""add_customizable_notification_settings

Revision ID: 27f823d35430
Revises: a6e3a21b88d8
Create Date: 2026-06-13 23:47:17.547453
"""
from alembic import op
import sqlalchemy as sa


revision = '27f823d35430'
down_revision = 'a6e3a21b88d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_email_report_configs', sa.Column('send_daily_summary', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_booking_created', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_booking_modified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_payment_captured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_payment_refunded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_entity_deleted', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_operations_daily', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_financial_critical', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('notify_backup_warnings', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('booking_email_template', sa.String(length=40), server_default='detailed', nullable=False))
    op.add_column('daily_email_report_configs', sa.Column('payment_email_template', sa.String(length=40), server_default='detailed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_email_report_configs', 'payment_email_template')
    op.drop_column('daily_email_report_configs', 'booking_email_template')
    op.drop_column('daily_email_report_configs', 'notify_backup_warnings')
    op.drop_column('daily_email_report_configs', 'notify_financial_critical')
    op.drop_column('daily_email_report_configs', 'notify_operations_daily')
    op.drop_column('daily_email_report_configs', 'notify_entity_deleted')
    op.drop_column('daily_email_report_configs', 'notify_payment_refunded')
    op.drop_column('daily_email_report_configs', 'notify_payment_captured')
    op.drop_column('daily_email_report_configs', 'notify_booking_modified')
    op.drop_column('daily_email_report_configs', 'notify_booking_created')
    op.drop_column('daily_email_report_configs', 'send_daily_summary')
    # ### end Alembic commands ###