"""add_groom_bride_to_customers

Revision ID: 36c89d0494e1
Revises: 20260402_000025
Create Date: 2026-04-21 23:13:15.289973
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '36c89d0494e1'
down_revision = '20260402_000025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_grid_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('table_key', sa.String(length=120), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_grid_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_grid_preferences')),
    sa.UniqueConstraint('user_id', 'table_key', name='uq_user_grid_preferences_user_table')
    )
    op.drop_index('ix_payment_receipts_booking_id', table_name='payment_receipts')
    op.drop_index('ix_payment_receipts_branch_id', table_name='payment_receipts')
    op.drop_index('ix_payment_receipts_company_id', table_name='payment_receipts')
    op.drop_index('ix_payment_receipts_journal_entry_id', table_name='payment_receipts')
    op.drop_index('ix_payment_receipts_payment_date', table_name='payment_receipts')
    op.drop_table('payment_receipts')
    op.drop_index('ix_custody_cases_case_number', table_name='custody_cases')
    op.drop_table('custody_cases')
    op.drop_index('ix_export_schedules_company_id', table_name='export_schedules')
    op.drop_index('ix_export_schedules_next_run_on', table_name='export_schedules')
    op.drop_table('export_schedules')
    op.drop_index('ix_booking_lines_booking_id', table_name='booking_lines')
    op.drop_index('ix_booking_lines_dress_id', table_name='booking_lines')
    op.drop_index('ix_booking_lines_service_date', table_name='booking_lines')
    op.drop_index('ix_bookings_branch_id', table_name='bookings')
    op.drop_index('ix_bookings_company_id', table_name='bookings')
    op.drop_index('ix_bookings_customer_id', table_name='bookings')
    op.drop_index('ix_bookings_event_date', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_constraint('fk_bookings_service_id_service_catalog_items', 'bookings', type_='foreignkey')
    op.drop_constraint('fk_bookings_dress_id_dress_resources', 'bookings', type_='foreignkey')
    op.drop_constraint('fk_bookings_revenue_journal_entry', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'quoted_price')
    op.drop_column('bookings', 'revenue_recognized_at')
    op.drop_column('bookings', 'dress_id')
    op.drop_column('bookings', 'service_id')
    op.drop_column('bookings', 'revenue_journal_entry_id')
    op.drop_column('bookings', 'event_date')
    op.add_column('customers', sa.Column('groom_name', sa.String(length=160), nullable=True))
    op.add_column('customers', sa.Column('bride_name', sa.String(length=160), nullable=True))
    op.add_column('customers', sa.Column('phone_2', sa.String(length=30), nullable=True))
    op.drop_index('ix_customers_company_id', table_name='customers')
    op.drop_index('ix_customers_full_name', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_departments_company_id', table_name='departments')
    op.drop_index('ix_departments_name', table_name='departments')
    op.drop_index('ix_dress_resources_code', table_name='dress_resources')
    op.drop_index('ix_dress_resources_company_id', table_name='dress_resources')
    op.drop_index('ix_dress_resources_status', table_name='dress_resources')
    op.drop_index('ix_payment_allocations_booking_id', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_booking_line_id', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_payment_document_id', table_name='payment_allocations')
    op.drop_index('ix_payment_documents_branch_id', table_name='payment_documents')
    op.drop_index('ix_payment_documents_company_id', table_name='payment_documents')
    op.drop_index('ix_payment_documents_customer_id', table_name='payment_documents')
    op.drop_index('ix_payment_documents_payment_date', table_name='payment_documents')
    op.drop_index('ix_service_catalog_company_id', table_name='service_catalog_items')
    op.drop_index('ix_service_catalog_department_id', table_name='service_catalog_items')
    op.drop_index('ix_service_catalog_name', table_name='service_catalog_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_catalog_name', 'service_catalog_items', ['name'], unique=False)
    op.create_index('ix_service_catalog_department_id', 'service_catalog_items', ['department_id'], unique=False)
    op.create_index('ix_service_catalog_company_id', 'service_catalog_items', ['company_id'], unique=False)
    op.create_index('ix_payment_documents_payment_date', 'payment_documents', ['payment_date'], unique=False)
    op.create_index('ix_payment_documents_customer_id', 'payment_documents', ['customer_id'], unique=False)
    op.create_index('ix_payment_documents_company_id', 'payment_documents', ['company_id'], unique=False)
    op.create_index('ix_payment_documents_branch_id', 'payment_documents', ['branch_id'], unique=False)
    op.create_index('ix_payment_allocations_payment_document_id', 'payment_allocations', ['payment_document_id'], unique=False)
    op.create_index('ix_payment_allocations_booking_line_id', 'payment_allocations', ['booking_line_id'], unique=False)
    op.create_index('ix_payment_allocations_booking_id', 'payment_allocations', ['booking_id'], unique=False)
    op.create_index('ix_dress_resources_status', 'dress_resources', ['status'], unique=False)
    op.create_index('ix_dress_resources_company_id', 'dress_resources', ['company_id'], unique=False)
    op.create_index('ix_dress_resources_code', 'dress_resources', ['code'], unique=False)
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.create_index('ix_departments_company_id', 'departments', ['company_id'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_full_name', 'customers', ['full_name'], unique=False)
    op.create_index('ix_customers_company_id', 'customers', ['company_id'], unique=False)
    op.drop_column('customers', 'phone_2')
    op.drop_column('customers', 'bride_name')
    op.drop_column('customers', 'groom_name')
    op.add_column('bookings', sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('revenue_journal_entry_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('service_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('dress_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('revenue_recognized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('quoted_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_bookings_revenue_journal_entry', 'bookings', 'journal_entries', ['revenue_journal_entry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_bookings_dress_id_dress_resources', 'bookings', 'dress_resources', ['dress_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_bookings_service_id_service_catalog_items', 'bookings', 'service_catalog_items', ['service_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_event_date', 'bookings', ['event_date'], unique=False)
    op.create_index('ix_bookings_customer_id', 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_company_id', 'bookings', ['company_id'], unique=False)
    op.create_index('ix_bookings_branch_id', 'bookings', ['branch_id'], unique=False)
    op.create_index('ix_booking_lines_service_date', 'booking_lines', ['service_date'], unique=False)
    op.create_index('ix_booking_lines_dress_id', 'booking_lines', ['dress_id'], unique=False)
    op.create_index('ix_booking_lines_booking_id', 'booking_lines', ['booking_id'], unique=False)
    op.create_table('export_schedules',
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('cadence', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('next_run_on', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_export_schedules_branch_id_branches', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_export_schedules_company_id_companies', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_export_schedules')
    )
    op.create_index('ix_export_schedules_next_run_on', 'export_schedules', ['next_run_on'], unique=False)
    op.create_index('ix_export_schedules_company_id', 'export_schedules', ['company_id'], unique=False)
    op.create_table('custody_cases',
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('dress_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('entity_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('case_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('compensation_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('compensation_collected_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('compensation_payment_document_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_custody_cases_branch_id_branches', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_custody_cases_company_id_companies', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compensation_payment_document_id'], ['payment_documents.id'], name='fk_custody_cases_compensation_payment_document_id_payme_902f', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_custody_cases_created_by_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_custody_cases_customer_id_customers', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dress_id'], ['dress_resources.id'], name='fk_custody_cases_dress_id_dress_resources', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_custody_cases_updated_by_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_custody_cases')
    )
    op.create_index('ix_custody_cases_case_number', 'custody_cases', ['case_number'], unique=False)
    op.create_table('payment_receipts',
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('payment_number', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('remaining_after', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('journal_entry_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('voided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('voided_by_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('void_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_payment_receipts_booking_id_bookings', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_payment_receipts_branch_id_branches', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_payment_receipts_company_id_companies', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name='fk_payment_receipts_journal_entry_id_journal_entries', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name='fk_payment_receipts_voided_by_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_payment_receipts'),
    sa.UniqueConstraint('company_id', 'payment_number', name='uq_payment_receipts_company_number')
    )
    op.create_index('ix_payment_receipts_payment_date', 'payment_receipts', ['payment_date'], unique=False)
    op.create_index('ix_payment_receipts_journal_entry_id', 'payment_receipts', ['journal_entry_id'], unique=False)
    op.create_index('ix_payment_receipts_company_id', 'payment_receipts', ['company_id'], unique=False)
    op.create_index('ix_payment_receipts_branch_id', 'payment_receipts', ['branch_id'], unique=False)
    op.create_index('ix_payment_receipts_booking_id', 'payment_receipts', ['booking_id'], unique=False)
    op.drop_table('user_grid_preferences')
    # ### end Alembic commands ###