"""add_disbursement_vouchers_table

Revision ID: 3b27e2662dab
Revises: 85f07777b40f
Create Date: 2026-05-18 15:02:40.198458
"""
from alembic import op
import sqlalchemy as sa


revision = '3b27e2662dab'
down_revision = '85f07777b40f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement_vouchers',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('updated_by_user_id', sa.String(), nullable=True),
    sa.Column('entity_version', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=40), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payee_type', sa.String(length=30), nullable=False),
    sa.Column('payee_id', sa.String(length=40), nullable=True),
    sa.Column('payee_name', sa.String(length=120), nullable=True),
    sa.Column('expense_category_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_user_id', sa.String(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_disbursement_vouchers_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_disbursement_vouchers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_disbursement_vouchers_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_disbursement_vouchers_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_disbursement_vouchers_payment_method_id_payment_methods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_disbursement_vouchers_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_disbursement_vouchers_voided_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disbursement_vouchers')),
    sa.UniqueConstraint('company_id', 'voucher_number', name='uq_disbursement_vouchers_company_number')
    )
    op.add_column('payment_allocations', sa.Column('disbursement_voucher_id', sa.String(), nullable=True))
    op.alter_column('payment_allocations', 'payment_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('uq_payment_allocations_document_line_number', 'payment_allocations', type_='unique')
    op.create_foreign_key(op.f('fk_payment_allocations_disbursement_voucher_id_disbursement_vouchers'), 'payment_allocations', 'disbursement_vouchers', ['disbursement_voucher_id'], ['id'], ondelete='CASCADE')
    op.add_column('reconciliation_items', sa.Column('disbursement_voucher_id', sa.String(), nullable=True))
    op.alter_column('reconciliation_items', 'payment_document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('fk_reconciliation_items_disbursement_voucher_id_disbursement_vouchers'), 'reconciliation_items', 'disbursement_vouchers', ['disbursement_voucher_id'], ['id'], ondelete='RESTRICT')
    
    # Custom Data Backfill & Migration logic
    connection = op.get_bind()
    results = connection.execute(sa.text("""
        SELECT pd.id, pd.company_id, pd.branch_id, pd.payment_method_id, pd.created_by_user_id,
               pd.updated_by_user_id, pd.entity_version, pd.payment_number, pd.payment_date,
               pd.direct_amount, pd.status, pd.journal_entry_id, pd.voided_at, pd.voided_by_user_id,
               pd.void_reason, pd.notes, pd.created_at, pd.updated_at,
               c.full_name AS customer_name, pd.customer_id
        FROM payment_documents pd
        LEFT JOIN customers c ON pd.customer_id = c.id
        WHERE pd.document_kind = 'refund'
    """)).fetchall()

    for row in results:
        # Check if there are allocations to calculate amount, otherwise use direct_amount
        alloc_sum = connection.execute(sa.text(
            "SELECT SUM(allocated_amount) FROM payment_allocations WHERE payment_document_id = :pd_id"
        ), {"pd_id": row.id}).scalar()
        amount = alloc_sum if alloc_sum is not None else row.direct_amount

        # Insert into disbursement_vouchers
        connection.execute(sa.text("""
            INSERT INTO disbursement_vouchers (
                id, company_id, branch_id, payment_method_id, created_by_user_id, updated_by_user_id,
                entity_version, voucher_number, voucher_date, amount, payee_type, payee_id, payee_name,
                status, journal_entry_id, voided_at, voided_by_user_id, void_reason, notes, created_at, updated_at
            ) VALUES (
                :id, :company_id, :branch_id, :payment_method_id, :created_by_user_id, :updated_by_user_id,
                :entity_version, :voucher_number, :voucher_date, :amount, 'customer', :payee_id, :payee_name,
                :status, :journal_entry_id, :voided_at, :voided_by_user_id, :void_reason, :notes, :created_at, :updated_at
            )
        """), {
            "id": row.id,
            "company_id": row.company_id,
            "branch_id": row.branch_id,
            "payment_method_id": row.payment_method_id,
            "created_by_user_id": row.created_by_user_id,
            "updated_by_user_id": row.updated_by_user_id,
            "entity_version": row.entity_version,
            "voucher_number": row.payment_number,
            "voucher_date": row.payment_date,
            "amount": amount,
            "payee_id": row.customer_id,
            "payee_name": row.customer_name or "",
            "status": row.status,
            "journal_entry_id": row.journal_entry_id,
            "voided_at": row.voided_at,
            "voided_by_user_id": row.voided_by_user_id,
            "void_reason": row.void_reason,
            "notes": row.notes,
            "created_at": row.created_at,
            "updated_at": row.updated_at
        })

    # Move allocations to point to disbursement_voucher_id
    connection.execute(sa.text("""
        UPDATE payment_allocations
        SET disbursement_voucher_id = payment_document_id, payment_document_id = NULL
        WHERE payment_document_id IN (SELECT id FROM payment_documents WHERE document_kind = 'refund')
    """))

    # Move reconciliation items to point to disbursement_voucher_id
    connection.execute(sa.text("""
        UPDATE reconciliation_items
        SET disbursement_voucher_id = payment_document_id, payment_document_id = NULL
        WHERE payment_document_id IN (SELECT id FROM payment_documents WHERE document_kind = 'refund')
    """))

    # Delete migrated records from payment_documents
    connection.execute(sa.text("DELETE FROM payment_documents WHERE document_kind = 'refund'"))

    # Rename remaining active receipts' prefix from PAY to REC in payment_documents
    connection.execute(sa.text("""
        UPDATE payment_documents
        SET payment_number = REPLACE(payment_number, 'PAY', 'REC')
        WHERE document_kind = 'collection' AND payment_number LIKE 'PAY%'
    """))

    # Rename references in journal_entries to REC
    connection.execute(sa.text("""
        UPDATE journal_entries
        SET reference = REPLACE(reference, 'PAY', 'REC')
        WHERE reference LIKE 'PAY%' AND id IN (
            SELECT journal_entry_id FROM payment_documents WHERE document_kind = 'collection'
        )
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reconciliation_items_disbursement_voucher_id_disbursement_vouchers'), 'reconciliation_items', type_='foreignkey')
    op.alter_column('reconciliation_items', 'payment_document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reconciliation_items', 'disbursement_voucher_id')
    op.drop_constraint(op.f('fk_payment_allocations_disbursement_voucher_id_disbursement_vouchers'), 'payment_allocations', type_='foreignkey')
    op.create_unique_constraint('uq_payment_allocations_document_line_number', 'payment_allocations', ['payment_document_id', 'line_number'])
    op.alter_column('payment_allocations', 'payment_document_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('payment_allocations', 'disbursement_voucher_id')
    op.drop_table('disbursement_vouchers')
    # ### end Alembic commands ###