"""add_frozen_index

Revision ID: 4247293855a1
Revises: 9df7e233573d
Create Date: 2026-05-14 00:26:19.842908
"""
from alembic import op
import sqlalchemy as sa


revision = '4247293855a1'
down_revision = '9df7e233573d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_is_frozen_until'), 'users', ['is_frozen_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_frozen_until'), table_name='users')
    # ### end Alembic commands ###