"""add_parent_booking_id

Revision ID: 4b30bac70b86
Revises: 5826d7b6c35d
Create Date: 2026-05-01 23:44:42.044290
"""
from alembic import op
import sqlalchemy as sa


revision = '4b30bac70b86'
down_revision = '5826d7b6c35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('parent_booking_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_bookings_parent_booking_id_bookings'), 'bookings', 'bookings', ['parent_booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_parent_booking_id_bookings'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'parent_booking_id')
    # ### end Alembic commands ###