"""add_booking_external_code

Revision ID: 5826d7b6c35d
Revises: 1503cf864b17
Create Date: 2026-04-26 23:27:59.272573
"""
from alembic import op
import sqlalchemy as sa


revision = '5826d7b6c35d'
down_revision = '1503cf864b17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('external_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'external_code')
    # ### end Alembic commands ###