"""add_registration_date_to_customers

Revision ID: 5f084ff4ae34
Revises: 36c89d0494e1
Create Date: 2026-04-21 23:29:37.164307
"""
from alembic import op
import sqlalchemy as sa


revision = '5f084ff4ae34'
down_revision = '36c89d0494e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'registration_date')
    # ### end Alembic commands ###