"""make_dress_description_optional

Revision ID: 848b7989e897
Revises: 87a642fd2086
Create Date: 2026-04-25 22:18:37.424911
"""
from alembic import op
import sqlalchemy as sa


revision = '848b7989e897'
down_revision = '87a642fd2086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custody_cases_case_number', table_name='custody_cases')
    op.drop_index('uq_custody_cases_booking_line_id', table_name='custody_cases')
    op.create_unique_constraint('uq_custody_cases_booking_line_id', 'custody_cases', ['booking_line_id'])
    op.alter_column('dress_resources', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dress_resources', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('uq_custody_cases_booking_line_id', 'custody_cases', type_='unique')
    op.create_index('uq_custody_cases_booking_line_id', 'custody_cases', ['booking_line_id'], unique=True)
    op.create_index('ix_custody_cases_case_number', 'custody_cases', ['case_number'], unique=False)
    # ### end Alembic commands ###