"""add_start_and_end_dates_to_reconciliation

Revision ID: 85f07777b40f
Revises: 1629a09ff94b
Create Date: 2026-05-17 20:22:37.686185
"""
from alembic import op
import sqlalchemy as sa


revision = '85f07777b40f'
down_revision = '1629a09ff94b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('cash_reconciliations', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('cash_reconciliations', sa.Column('end_date', sa.Date(), nullable=True))
    
    # Backfill existing data
    op.execute("UPDATE cash_reconciliations SET start_date = reconciliation_date, end_date = reconciliation_date WHERE start_date IS NULL OR end_date IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_reconciliations', 'end_date')
    op.drop_column('cash_reconciliations', 'start_date')
    # ### end Alembic commands ###