"""add is_dress_department and display_order

Revision ID: 87a642fd2086
Revises: 20260423_000028
Create Date: 2026-04-25 16:19:15.423553
"""
from alembic import op
import sqlalchemy as sa


revision = '87a642fd2086'
down_revision = '20260423_000028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_dress_department', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('departments', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('service_catalog_items', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_catalog_items', 'display_order')
    op.drop_column('departments', 'display_order')
    op.drop_column('departments', 'is_dress_department')
    # ### end Alembic commands ###