"""security_phase_1

Revision ID: 9df7e233573d
Revises: 3613ed6d4b26
Create Date: 2026-05-13 15:04:07.797871
"""
from alembic import op
import sqlalchemy as sa


revision = '9df7e233573d'
down_revision = '3613ed6d4b26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_2fa_backup_codes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_2fa_backup_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_2fa_backup_codes'))
    )
    op.add_column('audit_logs', sa.Column('previous_log_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('log_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_log_hash'), 'audit_logs', ['log_hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_previous_log_hash'), 'audit_logs', ['previous_log_hash'], unique=False)
    op.add_column('roles', sa.Column('is_preset', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_roles', sa.Column('branch_id', sa.String(), nullable=True))
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(op.f('fk_user_roles_branch_id_branches'), 'user_roles', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_frozen_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'is_frozen_until')
    op.drop_constraint(op.f('fk_user_roles_branch_id_branches'), 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'updated_at')
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'branch_id')
    op.drop_column('roles', 'is_preset')
    op.drop_index(op.f('ix_audit_logs_previous_log_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_hash'), table_name='audit_logs')
    op.drop_column('audit_logs', 'log_hash')
    op.drop_column('audit_logs', 'previous_log_hash')
    op.drop_table('user_2fa_backup_codes')
    # ### end Alembic commands ###