"""create daily email report configs table

Revision ID: a6e3a21b88d8
Revises: f2db232a60a8
Create Date: 2026-06-09 23:55:56.234215
"""
from alembic import op
import sqlalchemy as sa


revision = 'a6e3a21b88d8'
down_revision = 'f2db232a60a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_email_report_configs',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sender_email', sa.String(length=120), nullable=False),
    sa.Column('sender_password', sa.String(length=500), nullable=False),
    sa.Column('smtp_server', sa.String(length=120), server_default='smtp.gmail.com', nullable=False),
    sa.Column('smtp_port', sa.Integer(), server_default='587', nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('send_hour', sa.Integer(), server_default='21', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_daily_email_report_configs_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_email_report_configs'))
    )
    op.create_index(op.f('ix_daily_email_report_configs_company_id'), 'daily_email_report_configs', ['company_id'], unique=False)
    op.execute("DELETE FROM daily_email_report_logs")
    op.add_column('daily_email_report_logs', sa.Column('config_id', sa.String(), nullable=False))
    op.drop_index('ix_daily_email_report_logs_report_date', table_name='daily_email_report_logs')
    op.create_index(op.f('ix_daily_email_report_logs_report_date'), 'daily_email_report_logs', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_email_report_logs_config_id'), 'daily_email_report_logs', ['config_id'], unique=False)
    op.create_unique_constraint('uq_daily_report_config_date', 'daily_email_report_logs', ['config_id', 'report_date'])
    op.create_foreign_key(op.f('fk_daily_email_report_logs_config_id_daily_email_report_configs'), 'daily_email_report_logs', 'daily_email_report_configs', ['config_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_daily_email_report_logs_config_id_daily_email_report_configs'), 'daily_email_report_logs', type_='foreignkey')
    op.drop_constraint('uq_daily_report_config_date', 'daily_email_report_logs', type_='unique')
    op.drop_index(op.f('ix_daily_email_report_logs_config_id'), table_name='daily_email_report_logs')
    op.drop_index(op.f('ix_daily_email_report_logs_report_date'), table_name='daily_email_report_logs')
    op.create_index('ix_daily_email_report_logs_report_date', 'daily_email_report_logs', ['report_date'], unique=True)
    op.drop_column('daily_email_report_logs', 'config_id')
    op.drop_index(op.f('ix_daily_email_report_configs_company_id'), table_name='daily_email_report_configs')
    op.drop_table('daily_email_report_configs')
    # ### end Alembic commands ###